<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ClientWSDL" targetNamespace="http://www.anardvir.com/WebServiceContracts/ClientWSDL/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.anardvir.com/WebServiceContracts/ClientWSDL/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://www.anardvir.com/WebServiceContracts/ClientWSDL/UserElementType">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.anardvir.com/WebServiceContracts/ClientWSDL/">
			<xsd:import namespace="http://www.anardvir.com/WebServiceContracts/ClientWSDL/UserElementType" schemaLocation="./ElementTypes/UserElementType.xsd"/>
		</xsd:schema>
  </wsdl:types>
  <wsdl:message name="loginRequest">
    <wsdl:part name="userRequest" element="ns0:user">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="loginResponse">
    <wsdl:part name="userResponse" element="ns0:user">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ClientPort">
    <wsdl:operation name="login">
<wsdl:documentation>Provide login authentication service</wsdl:documentation>
      <wsdl:input name="userRequest" message="tns:loginRequest">
    </wsdl:input>
      <wsdl:output name="userReturn" message="tns:loginResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ClientBinding" type="tns:ClientPort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="login">
      <soap:operation soapAction="login"/>
      <wsdl:input>
        <soap:body parts="userRequest" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="userResponse" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ClientService">
    <wsdl:port name="ClientPort" binding="tns:ClientBinding">
      <soap:address location="http://localhost:8080/TaskManagmentSystemFrontEndModule/services/ClientPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
