
package com.anardvir.webservicecontracts.clientwsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.4
 * 2012-08-10T19:04:47.789+03:00
 * Generated source version: 2.5.4
 * 
 */
public final class ClientPort_ClientPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.anardvir.com/WebServiceContracts/ClientWSDL/", "ClientService");

    private ClientPort_ClientPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClientService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClientService ss = new ClientService(wsdlURL, SERVICE_NAME);
        ClientPort port = ss.getClientPort();  
        
        {
        System.out.println("Invoking login...");
        com.anardvir.webservicecontracts.clientwsdl.userelementtype.UserElementType _login_userRequest = new com.anardvir.webservicecontracts.clientwsdl.userelementtype.UserElementType();
        _login_userRequest.setEmail("Email-1716091272");
        _login_userRequest.setFirstName("FirstName1104228805");
        _login_userRequest.setLastName("LastName1243779834");
        _login_userRequest.setUserName("UserName1468396247");
        _login_userRequest.setPassword("Password1084910517");
        _login_userRequest.setId(-2015564162);
        com.anardvir.webservicecontracts.clientwsdl.userelementtype.UserElementType _login__return = port.login(_login_userRequest);
        System.out.println("login.result=" + _login__return);


        }

        System.exit(0);
    }

}
