package com.anardvir.webservicecontracts.clientwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.4
 * 2012-08-07T20:29:13.761+03:00
 * Generated source version: 2.5.4
 * 
 */
@WebService(targetNamespace = "http://www.anardvir.com/WebServiceContracts/ClientWSDL/", name = "ClientPort")
@XmlSeeAlso({com.anardvir.webservicecontracts.clientwsdl.userelementtype.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClientPort {

    /**
     * Provide login authentication service
     */
    @WebResult(name = "user", targetNamespace = "http://www.anardvir.com/WebServiceContracts/ClientWSDL/UserElementType", partName = "userResponse")
    @WebMethod(action = "login")
    public com.anardvir.webservicecontracts.clientwsdl.userelementtype.UserElementType login(
        @WebParam(partName = "userRequest", name = "user", targetNamespace = "http://www.anardvir.com/WebServiceContracts/ClientWSDL/UserElementType")
        com.anardvir.webservicecontracts.clientwsdl.userelementtype.UserElementType userRequest
    );
}
