package com.anardvir.webservicecontracts.clientwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.4
 * 2012-07-28T18:21:23.166+03:00
 * Generated source version: 2.5.4
 * 
 */
@WebService(targetNamespace = "http://www.anarDvir.com/WebServiceContracts/ClientWSDL/", name = "ClientWSDL")
@XmlSeeAlso({com.anardvir.webservicecontracts.clientwsdl.userelementtype.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClientWSDL {

    /**
     * Provide login authentication service
     */
    @WebMethod(operationName = "UserAuthentication", action = "http://www.anarDvir.com/WebServiceContracts/ClientWSDL/UserAuthentication")
    public void userAuthentication(
        @WebParam(partName = "user", mode = WebParam.Mode.INOUT, name = "user", targetNamespace = "http://www.anarDvir.com/WebServiceContracts/ClientWSDL/UserElementType")
        javax.xml.ws.Holder<com.anardvir.webservicecontracts.clientwsdl.userelementtype.UserElementType> user
    );
}
