
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.anardvir.webservicecontracts.clientwsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.4
 * 2012-07-28T18:21:23.100+03:00
 * Generated source version: 2.5.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "ClientWSDL",
                      portName = "ClientWSDLSOAP",
                      targetNamespace = "http://www.anarDvir.com/WebServiceContracts/ClientWSDL/",
                      wsdlLocation = "http://www.anarDvir.com/?wsdl",
                      endpointInterface = "com.anardvir.webservicecontracts.clientwsdl.ClientWSDL")
                      
public class ClientWSDLImpl implements ClientWSDL {

    private static final Logger LOG = Logger.getLogger(ClientWSDLImpl.class.getName());

    /* (non-Javadoc)
     * @see com.anardvir.webservicecontracts.clientwsdl.ClientWSDL#userAuthentication(com.anardvir.webservicecontracts.clientwsdl.userelementtype.UserElementType  user )*
     */
    public void userAuthentication
    (javax.xml.ws.Holder<com.anardvir.webservicecontracts.clientwsdl.userelementtype.UserElementType> user) { 
        LOG.info("Executing operation userAuthentication");
        System.out.println(user.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
